### ISSUE TITLE
server url is not correct

### ISSUE THREAD

**Issue by kadogo** [ikalnytskyi/sphinxcontrib-redoc#29] opened 2019-05-16 15:44 UTC
Hello,

After running "make html" if I look at the documentation I have the next server URL

```
http://demo-custom.fusiondirectory.org/login
```

But normally it must be "http://demo-custom.fusiondirectory.org/fusiondirectory/rest.php/login".
From where come the server url ?

Cheers.

**Comment by ikalnytskyi** [comment] 2019-05-16 18:50
Hey @kadogo,

Can you give more details please? I'm not sure I understand what server URL you are talking about. Is it a one from OpenAPI spec? Where exactly a wrong URL is shown?

**Comment by kadogo** [comment] 2019-05-16 20:48
Hello @ikalnytskyi 

It's the URL that is shown in the documentation that it's wrong.

In the openapi.yaml (http://demo-custom.fusiondirectory.org/fusiondirectory/rest.php/openapi.yaml 
) I see the following informations.

```
servers:
- url: https://demo-custom.fusiondirectory.org/fusiondirectory/rest.php
```

So I think that normally it would show https://demo-custom.fusiondirectory.org/fusiondirectory/rest.php/login and not http://demo-custom.fusiondirectory.org/login

**Comment by kadogo** [comment] 2019-05-17 09:29
At end it work now that I use the latest standalone version of redoc 

```
redoc_uri = 'https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js'
```

**Comment by ikalnytskyi** [comment] 2019-06-08 15:38
@kadogo sorry for not responding so long. As I understand it now, the problem is in redoc itself. ReDoc v2 is in RC state now. Once it's release, I'll update this package to bundle the latest version of ReDoc. 

Closing this issue now because the workaround is to explicitly use newer version.

**Closed as completed by ikalnytskyi** 2019-06-08 15:38 UTC
